# based on this
# https://gist.github.com/dan-blanchard/7045057
language: python
sudo: false
python:
  - 2.7
#  - 3.3
notifications:
  email: false

# Setup anaconda
before_install:
# python 3 needs something different
  - pip install codecov
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
# Install packages
install:
  - conda create --yes -n test_env python=$TRAVIS_PYTHON_VERSION pip nose numpy=1.9.3 cython scipy=0.16.0
  # can we make this optional?
  - conda install --yes -n test_env -c mforbes pyfftw
  - source activate test_env
# build the kernel in the local dir
  - python setup.py build_ext --inplace
# not necessary to actually install
# nose will import the pacakge from the working directory
#  - python setup.py install

# Run test
script:
  - nosetests -v
# Calculate coverage
after_success:
# codecov can't be found because we are in virtual environment? no that doesn't seem right
#  - source deactivate
  - codecov
#  - coveralls --config_file .coveragerc
